### ISSUE TITLE
Зеркало для скачивания приложения

### ISSUE THREAD

**Issue by kostya-php** [ermig1979/AntiDupl#10]
Уважаемый автор. Если есть возможность, добавь пожалуйста альтернативные источники для скачивания. С территории Крыма нет возможности скачивать с сайта sourceforge.net, наложены санкции.

**Comment by ermig1979** [comment]
Ок. Я что-нибудь придумаю.

**Comment by WonderRat** [comment]
https://github.com/ermig1979/AntiDupl/releases

**Comment by valsaven** [comment]
Added. Check https://github.com/ermig1979/AntiDupl/releases
