### ISSUE TITLE
.NET Core GUI app

### ISSUE THREAD

**Issue by Gigas002** [ermig1979/AntiDupl#101]
Do you consider moving the app on modern framework? If so, I can provide a PR with updated `AntiDupl.NET.csproj` file, so it can be built under `netcoreapp3.1` (requires [dotnet core 3.1.100 SDK](https://dotnet.microsoft.com/download/dotnet-core/3.1) or newer to build). I've also tried `net5.0` (preview.5), but it didn't work out yet.

**Comment by heinrichI** [comment]
Там работает WinForms или WPF?

**Comment by Gigas002** [comment]
Работают оба еще с релиза 3.0. В WinForms, правда, до сих пор не полностью дизайнер в VS2019 поддерживается, но это мелочь.
