### ISSUE TITLE
REQ: Select/Delete by Dimension

### ISSUE THREAD

**Issue by rcodehub** [ermig1979/AntiDupl#105]
One thing that is missing and is really needed is the ability to select/mark/delete duplicates by photo dimension.

Currently it's only possible to delete the first or second image of a group, but if 90% of duplicates are the same dimension, 5% are larger in the first picture and 5% are larger in the second image there's no "easy" way of keeping the best photos from each grouping without processing each group one by one.

**Comment by heinrichI** [comment]
I tried to do something like this in WPF version https://github.com/ermig1979/AntiDupl/issues/57#issuecomment-487377786:
![image](https://user-images.githubusercontent.com/7752557/98368339-9ee1c200-2050-11eb-8fb4-ab14df48f3b4.png)
![image](https://user-images.githubusercontent.com/7752557/98368715-3810d880-2051-11eb-8179-8f592d304461.png)

Is this what you want?

**Comment by valsaven** [comment]
Please check @heinrichI comment. If it doesn't help, reopen the issue.
