### ISSUE TITLE
VirusTotal report

### ISSUE THREAD

**Issue by ThePrinSky** [ermig1979/AntiDupl#106]
I understand there are such things as false positives, and this may be that, but VirusTotal also reports that this file opens or tampers the following files:

Files Opened:
C:\Windows\system32\version.dll 
C:\Users\<USER>\Downloads\DXGIDebug.dll 
C:\Windows\system32\sfc_os.dll 
C:\Windows\system32\SSPICLI.DLL 
C:\Windows\system32\rsaenh.dll 
C:\Windows\system32\UXTheme.dll 
C:\Windows\system32\dwmapi.dll 
C:\Windows\system32\cryptbase.dll 
C:\Users\<USER>\Downloads\lpk.dll 
C:\Users\<USER>\Downloads\usp10.dll
Registry Keys Opened:
HKCR\CLSID\{FAE3D380-FEA4-4623-8C75-C6B61110B681}\Instance 
HKCR\CLSID\{FAE3D380-FEA4-4623-8C75-C6B61110B681}\Instance\Disabled 
HKLM\Software\Microsoft\Windows\CurrentVersion\Internet Settings 
HKLM\Software\Policies\Microsoft\Windows\CurrentVersion\Internet Settings 
HKLM\Software\Policies\Microsoft\Windows\CurrentVersion\Internet Settings\CreateUriCacheSize 
HKCU\Software\Microsoft\Windows\CurrentVersion\Internet Settings\CreateUriCacheSize 
HKLM\Software\Policies\Microsoft\Windows\CurrentVersion\Internet Settings\EnablePunycode 
HKCU\Software\Microsoft\Windows\CurrentVersion\Internet Settings\EnablePunycode 
HKCU\Software\Microsoft\Internet Explorer\Main\FeatureControl\FEATURE_HTTP_USERNAME_PASSWORD_DISABLE 
HKLM\Software\Microsoft\Internet Explorer\Main\FeatureControl\FEATURE_HTTP_USERNAME_PASSWORD_DISABLE\AntiDupl.NET-2.3.10.exe

**Comment by KoalaBear84** [comment]
See #85

**Comment by ThePrinSky** [comment]
Thanks. Will be looking for a better site than VirusTotal.
