### ISSUE TITLE
Output result in file or stdout

### ISSUE THREAD

**Issue by CrendKing** [ermig1979/AntiDupl#107]
It would be awesome if AntiDupl could export the search result into a file, so that user could further process the duplicates with other programs, instead of limiting to the actions in the application.

For example, here is an use case: one could have many videos in a library, some of them being duplicate, but not exactly same (vary in dimension, bitrate or fps). One way to find these duplicate is to take some thumbnails with ffmpeg, then compare these thumbnails (where AntiDupl is the excellent tool for that task). Once duplicates are found, instead of removing the images, what's needed is to remove the source video. If we can get the results in JSON or XML file, one can easily write a script to automatically remove the duplicate videos.

On a second thought, it does not need to be exactly "export results to file". Any form of output is enough. Imagine we can run AntiDupl as a command line, which takes the search profile file and target search directories as arguments, and output results in stdout, that would work too.

**Comment by ermig1979** [comment]
From help:

_How do I get a list of the results in text format?_

Select list of results with using key combination Ctrl-A. Copy to clipboard with using key combination Ctrl-C. Then copy it into your text file with using key combination Ctrl-V.

**Comment by CrendKing** [comment]
Excellent. My bad missing that bullet. My only suggestion would be adding relevant menuitems (File -> Save results, Edit -> Copy/Paste) to the GUI to make it more user friendly so that people can find the feature even without referring to the help.

Feel free to close this ticket though.
