### ISSUE TITLE
REQ: "Open containing folder" option

### ISSUE THREAD

**Issue by campbellkerr** [ermig1979/AntiDupl#119]
I would like the option to open the folder containing the duplicate image in Explorer.

For example, I scan with AntiDupl, and I find a duplicate that's a long lost photo. I would like to be able to explore that folder and see what else is in there.

There are other use cases I'm sure. Thanks!

**Comment by ermig1979** [comment]
This functionality has been already available (just click right mouse button on image):
https://ermig1979.github.io/AntiDupl/data/help/english/index.html?page=preview.html
