### ISSUE TITLE
REQ: Option to delete both files

### ISSUE THREAD

**Issue by campbellkerr** [ermig1979/AntiDupl#120]
Use case:

Antidupl gives me the option of deleting one or the other of the duplicate. 

If it finds 2 of the same photo that I don't want/care about, I would like to just delete both pics right there and then.

Thanks!

**Comment by ermig1979** [comment]
This functionality has been already available :
https://ermig1979.github.io/AntiDupl/data/help/english/index.html?page=preview.html
