### ISSUE TITLE
Feature request: Checksum comparison

### ISSUE THREAD

**Issue by mkaatman** [ermig1979/AntiDupl#124]
The functionality is great. I'd love to do a first pass where it was looking for literally identical files. Maybe there's a way to achieve this now?

**Comment by ermig1979** [comment]
See the column "Difference" - it displays the percentage mean-square difference of content of pictures of duplicate pair. **If the images are fully identical, the difference is shown in green.**

https://ermig1979.github.io/AntiDupl/data/help/english/index.html?page=table.html
