### ISSUE TITLE
Is WPF version working/supported?

### ISSUE THREAD

**Issue by moon6969** [ermig1979/AntiDupl#128]
I've been trying to build the WPF solution in v2.3.10, but can't get it working.

I've downloaded the [v2.3.10 source zip](https://github.com/ermig1979/AntiDupl/archive/refs/tags/v2.3.10.zip).

It contains what appears to be separate WinForm (AntiDupl\AntiDupl.NET) and WPF solutions (AntiDuplWPF\AntiDuplWPF).... what's the difference? ie: Are they both current and working?

I can build the WinForm version successfully, but just can't figure out the WPF build issues.

Both WinForms and WPF solutions have their own copy of the AntiDupl C++ engine, but there are significant differences in the v2.3.10 sources.

The first difference I investigated seems to be that that OpenJpeg library version has been updated from 1.x to 2.3.0 ... this is a breaking change that appears to have been implemented in the WinForm solution but not the WPF one. (Deduced from the OpenJpeg constant renames CODEC_JP2 vs OPJ_CODEC_JP2 etc.).

WPF solution also includes references to OpenNN and tinyxml 3rd party libraries, but these are not included in v2.3.10 source zip (but the other referenced libraries like LibOpenJpg and Simd are).

It would be great if someone could provide some simple build notes for the WPF solution. Even something like:
- Unzip v2.3.10.zip
- git clone OpenNN (version?) to folder "3rd"
- git clone tinyxml (version?) to folder "3rd"
- nuget System.Windows.Interactivity.WPF
- Open in VS (2019?)
- Select solution platform (which?)
- build

I also had a bash at building the WPF solution from the master branch, but as well as the OpenJpeg version issues, it's got all sorts of extra issues with the paths to the 3rd party library projects (simd in particular).

**Comment by heinrichI** [comment]
I started doing the WPF version, but it is abandoned. If you want to make her normal, I can advise you. I myself have been interested in recent years in releasing algorithms that would find small matching details in images.

**Comment by moon6969** [comment]
Ahh! thanks. I am actually looking at just using the C++ AntiDupl engine directly in my own project - I just wanted to experiment with the WPF app to see if it's feasible and if so, figure out the interface. So I can just use the winforms version.
