### ISSUE TITLE
Настройки не сохраняются

### ISSUE THREAD

**Issue by algot** [ermig1979/AntiDupl#14]
Установил новую версию AntiDupl на Win10/64
Открываю, добавляю паку для сканирования, сканирование завершается и выдает результаты.
Закрываю программу.
Открываю заново - все настройки сброшены на дефолтные: папка сканирования по умолчанию, результатов сканирования нет.

Пробовал на разных наборах данных.

Предыдущая версия работала нормально.

**Comment by ermig1979** [comment]
Скорее всего не прав доступа на запись в директорию, куда установлена программа.

**Comment by algot** [comment]
@ermig1979 Права на папки есть, запускаю под админом - все равно не сохраняет

**Comment by algot** [comment]
@ermig1979 
Нашёл причину. Я распаковывал новую версию в папку со старой с заменой фалов.
Распаковал с нуля - всё заработало.
