### ISSUE TITLE
New release

### ISSUE THREAD

**Issue by dajotim937** [ermig1979/AntiDupl#147]
Hi. May we have a new build/release? It's more that 2 years since last one. Thank you.

**Comment by KoalaBear84** [comment]
That would be escpecially helpfull because I cannot get it build and build a release myself. Tried it a year ago, tried it today. It doesn't start when I build it myself.

It generates a C:\Users\<username>\AppData\Local\CrashDumps here, but I don't have experience debugging CrashDumps.

**Comment by bconte** [comment]
Also was looking for a latest release

**Comment by yangjieshao** [comment]
Also was looking for a latest release

**Comment by yangjieshao** [comment]
> Also was looking for a latest release

[win-x86.zip](https://github.com/ermig1979/AntiDupl/files/10173244/win-x86.zip)

**Comment by Zungao** [comment]
> > Also was looking for a latest release
> 
> [AntiDupl.NET framework4.5.zip](https://github.com/ermig1979/AntiDupl/files/10173320/AntiDupl.NET.framework4.5.zip)

In Windows 10 and 11 x64 this still demands installation of Net Framework 3.5.

**Comment by Edi61** [comment]
> > > Also was looking for a latest release
> > 
> > 
> > [AntiDupl.NET framework4.5.zip](https://github.com/ermig1979/AntiDupl/files/10173320/AntiDupl.NET.framework4.5.zip)
> 
> In Windows 10 and 11 x64 this still demands installation of Net Framework 3.5.
-> Fixed by new commit https://github.com/ermig1979/AntiDupl/commit/6b4b75e139b70fcf9f4f09b89bc16fc6ce75c1de

**Comment by Zungao** [comment]
I tried the AntiDupl.NET-2.3.11 build available inhttps://github.com/ermig1979/AntiDupl/actions/runs/4324163470

**Comment by Zungao** [comment]
I tried the AntiDupl.NET-2.3.11 build made available [here](https://github.com/ermig1979/AntiDupl/actions/runs/4324163470) and now it requires .Net Desktop Runtime 6.0.14 (tried on both Windows 10 and 11)

My problem is that I use Antidupl in a portable mode and must not depend on the installation of any additional software other that the standard Windows installation. For this reason I still use Antidupl 2.3.6, witch is the last version that allows this :-(

Would a fully self contained program be possible?

**Comment by Edi61** [comment]
Hello @Zungao :
I have created a singlefile portable in my fork:
https://github.com/Edi61/AntiDupl/suites/11484024548/artifacts/593178905
But beware since all is included its a big file and its runs principially slower:
Could you please test it?

**Comment by SMylk** [comment]
> Hello @Zungao : I have created a singlefile portable in my fork: https://github.com/Edi61/AntiDupl/suites/11484024548/artifacts/593178905 But beware since all is included its a big file and its runs principially slower: Could you please test it?

404

**Comment by Edi61** [comment]
https://github.com/Edi61/AntiDupl/actions/runs/4394401067#artifacts
or try here under Artifacts -> AntiDupl.NET-2.3.11 build SingleFilePortable

**Comment by SMylk** [comment]
Thanks that works! Testing now.

**Comment by Zungao** [comment]
Hello @Edi61:  The zip file contains a 7z file (AntiDupl.NET-2.3.11_SingleFilePortable.7z) and a self extract z7 file
(AntiDupl.NET-2.3.11_SingleFilePortable.exe) which appear to contain the same files. Is this deliberate?

Both AntiDupl.NET.WinForms.exe and AntiDupl.NET.WPF.exe run without demanding any dependencies - THANK YOU!

I took some time to test and found nothing wrong. Will report if I find some bugs.

Again, thank you for taking the time to do this version!
