### ISSUE TITLE
[Serious bug] Can no longer select folders

### ISSUE THREAD

**Issue by lowercase-donkey** [ermig1979/AntiDupl#148]
When I try to select or change a folder, all I get is this:

![image](https://user-images.githubusercontent.com/28416282/203610363-675ebbfe-684d-4d48-bcdd-2620bfa090b0.png)

`Desktop` cannot be expanded in any way.

My current windows version: 
![image](https://user-images.githubusercontent.com/28416282/203610484-d681c14c-8fa3-4f94-ab77-ff0ffb0aecba.png)

For those that need a workaround, you can edit the default starting location in the XML:

![image](https://user-images.githubusercontent.com/28416282/203610913-ec12927d-d58f-4be4-97d4-8c55a4b62ee4.png)

This obviously is still very limiting.

I do note #143; hopefully this is already fixed internally and we get a release soon. Thanks!

**Comment by shnabors** [comment]
I've been experiencing the same problem for a couple of weeks now

**Comment by yami-no-tusbas** [comment]
Same here too, seems to be caused by the new "explorer" version

**Comment by Edi61** [comment]
Hi, 

I could not reproduce this error, it seems to work. Did you do something special before or its always happenning if you click on Add/Change Folder?
My windows version is:
![image](https://user-images.githubusercontent.com/84682915/212720415-52f38492-74b3-40f5-ae22-b7b4878fd677.png)

**Comment by yami-no-tusbas** [comment]
Oh god windows onedrive is so stupid... Thx for the solution !

**Comment by Edi61** [comment]
Solved and not a bug -> Closed
