### ISSUE TITLE
Replace file in the selection.

### ISSUE THREAD

**Issue by Monk69bl** [ermig1979/AntiDupl#150]
Hi 
When I right click and Chose replace 1st picture by 2nd picture in selected results.

It is actually doing the opposite.  It keeps the 1st picture and deletes the 2nd one.

![Capture](https://user-images.githubusercontent.com/120059076/206301673-b46ab74c-6f59-49c3-9a7e-e2c77b8a1bbd.JPG)
![Capture1](https://user-images.githubusercontent.com/120059076/206301843-86893087-3eb9-4889-9cdf-6109ae652984.JPG)

**Comment by dajotim937** [comment]
Yes.

**Comment by Monk69bl** [comment]
Thank you dajotim937
