### ISSUE TITLE
Rotated photos showing un-rotated. 

### ISSUE THREAD

**Issue by whitecat** [ermig1979/AntiDupl#158]
I am using Windows 11. Version 2.3.10. Photos that are rotated show up in the application as un-rotated.

Steps to reproduce:

1. Make a folder with a photo
2. Make a copy of the photo
3. Rotate the copy
4. Run AntiDupl on the folder

Expected behaviour
The AntiDupl will show the copy rotated and the original correct

Actual behaviour
The copied photo and the original photos are both the same orientation.

**Comment by Edi61** [comment]
Hello whitecat,

which kind of image is it?
Could you post a sample image file?

regards

**Comment by whitecat** [comment]
Here is a sample image
![2image6885](https://user-images.githubusercontent.com/122229/214961436-4de6825f-bf89-40f7-829f-fdeb1e35f6a8.jpg)

**Comment by Edi61** [comment]
Hi whitecat,

the rotation information in the second picture is stored in the EXIF metadata (-> Rotate 270 CW).
That's currently not considered by AntiDupl neither for comparision nor for viewing the image.

Regards,

**Comment by whitecat** [comment]
Thank you for the feedback. Both windows and mac only update the EXIF data when rotating. I would need to use a tool to read the EXIF and actually rotate the image.
