### ISSUE TITLE
How can i build this project?

### ISSUE THREAD

**Issue by Gitubhu** [ermig1979/AntiDupl#159]
i´m interested in building this project for my personal use, but i don't know how, so a guide would be very helpful.
I use Windows 10 64 bits

**Comment by ermig1979** [comment]
See 'dev' brunch. It can be built with Visual Studio 2022.

**Comment by Edi61** [comment]
For master brunch;
1. Install Visual Studio Community Edititon 2022 (Select at least .Net and Desktop C++ development and v143 buildtools)
3. Download vcpkg from github
e.g. by git clone https://github.com/Microsoft/vcpkg.git
4. Install vcpkg from command tool
cd vcpkg
./bootstrap-vcpkg.bat
./vcpkg integrate install
5. Download Antidupl from git and open src/AntiDupl/AntiDupl.sln
6. Build Antidupl with Visual Studio

**Comment by ermig1979** [comment]
May be it be reasonable to add those instructions to README.md ?

**Comment by Gitubhu** [comment]
Thanks a lot to both of you for your help.

**Comment by Gitubhu** [comment]
I need help with a problem.
If i had Visual studio installed the program runs fine, but if i uninstall visual studio the program doesn´t run.
I´m not interested in having visual studio installed.
Is there any way to run the program without having visual studio installed?

**Comment by Edi61** [comment]
There should be no dependecy to Visual.
Did you copy the whole folder structure including all dll files?
Only .exe file will not work.

**Comment by ermig1979** [comment]
It also need copy file 'AntiDupl.NET.runtimeconfig.json'.

**Comment by Gitubhu** [comment]
I rebuild the program and is working fine now.
