### ISSUE TITLE
Where did the third-party sources go?

### ISSUE THREAD

**Issue by heinrichI** [ermig1979/AntiDupl#167]
Куда делись исходники третьих сторон?
Я понимаю смысла дублировать нет Simd, его просто включить как под репозиторий. Но а остальные? Решил пул-реквест проверить, а уже ничего не собирается.

I understand there is no point in duplicating Simd, just include it as a repository. But what about the rest? I decided to check the pull request, but nothing is builded.

**Comment by Edi61** [comment]
See Readme.md:
Download and install vcpkg dependency manager

**Comment by heinrichI** [comment]
Thanks. vcpkg cool.
