### ISSUE TITLE
French language

### ISSUE THREAD

**Issue by toto1515** [ermig1979/AntiDupl#168]
hello,
I just make a french.xml file for french translation. 
The attached file is a text file you just have to rename to French.xml and place it in data\resources\strings folder
[French.txt](https://github.com/ermig1979/AntiDupl/files/10954946/French.txt)

**Comment by ermig1979** [comment]
Thank you! I added this file.

**Comment by Edi61** [comment]
Commit c86443028040e8becdad71ad44daf7a4f2414440 closes #168
