### ISSUE TITLE
German Language File

### ISSUE THREAD

**Issue by clickfisher** [ermig1979/AntiDupl#176]
Hello, I have translated the new version of AntiDouble.NET (2.3.11) into German language, see attachment. 

Best regards,

Arno (clickfish)
[German.zip](https://github.com/ermig1979/AntiDupl/files/11424820/German.zip)

**Comment by ermig1979** [comment]
Hi! I added your translation into German to the master. Thank you!

**Comment by clickfisher** [comment]
Hi, here's an optimized language file (I had forgotten a word).

Greetings from Waldenburg, Saxony

Arno

Am Di., 9. Mai 2023 um 18:23 Uhr schrieb Ihar Yermalayeu <
***@***.***>:
