### ISSUE TITLE
Fresh Install Crashes

### ISSUE THREAD

**Issue by LookingForWayOut** [ermig1979/AntiDupl#18]
Just installed AntiDupl.NET 2.3.9 on fresh install of Windows 7 Ultimate 32 bit.
One the program starts to scan for images, it will crash.
Any thoughts as to why? I can not seem to get it to give me any debug info.

**Comment by LookingForWayOut** [comment]
I have found, so far, 2.3.8 works fine still. I started off with small folders and it not crashed. I did one big folder and still went strong, where 2.3.9 would crash within seconds.

**Comment by valsaven** [comment]
#7
