### ISSUE TITLE
Error: does not work with AVIF format.

### ISSUE THREAD

**Issue by OFFOSORG** [ermig1979/AntiDupl#182]
Good day.

AVIF support has been added to the description. However, this is not in the version 2.3.11 release.
I was able to compile the sources myself. AVIF began to be seen in the interface, but files of this format are not loaded by the program and, accordingly, do not participate in the search for duplicates.

Through debugging I got to the point of loading an image in C++ but it fails.
I was able to enable debug logging via #define AD_DUMP_ENABLE in adConfig.h.
As a result, the debug log contains the error "No codec available".
At the source level, I also tracked the response status: "AVIF_RESULT_NO_CODEC_AVAILABLE".
It seems that this is somehow related directly to "libavif", perhaps due to the fact that they had a release not so long ago.
https://github.com/AOMediaCodec/libavif
And now, by default, no codec is selected; you need to register it yourself during assembly.
Unfortunately, I’m not good at automatically building projects, and I don’t know how to pass at least some parameters when building “libavif”, especially since “vcpkg” with its own “repository” is used for this.

I kindly ask you to release the next version with AVIF support. You have already done all the main work, all that remains is to figure out why the files are not readable.
If the release is “impossible,” then perhaps you can tell me what and where needs to be written in order for this format to work correctly.

Thank you in advance!

**Comment by kiawizard** [comment]
@ermig1979 Please build a version with jxl support, waiting for it :-)

**Comment by ermig1979** [comment]
Hi! I am going to do new release. But I want to update list of authors. The main last contributions were made by @Edi61 and it will be greate if he (or she) give me more personal information about  yourself.
