### ISSUE TITLE
My impression is the app is NOT getting any support

### ISSUE THREAD

**Issue by dec-mail** [ermig1979/AntiDupl#195]
My impression is the app is NOT getting any support

i see open issues here going back YEARS
i do not see any developer responses to pretty much ANYTHING.

comments?

**Comment by valsaven** [comment]
The latest version came out a few months ago. The author of the program often replies in issues.
And don't forget that it is open source. No one owes you anything. If you have a problem - the source code is open source. Please solve it and create a pull request.

**Comment by dec-mail** [comment]
Noted
