### ISSUE TITLE
AntiDupl now just crashes every time i try to run app ...

### ISSUE THREAD

**Issue by dec-mail** [ermig1979/AntiDupl#197]
After starting to use Antidupl, which i found was a totally wonderful app, after trying so many others, now, suddenly when i try to use it, it just almost immediately silently crashes

ie it opens,but crashes when i try to use

i can't really show you any screenshot because it just closes/crashes.

**Comment by dec-mail** [comment]
i reinstalled latest files.
same prob. it opens. it starts. and then it just silently closed.

![ShareX-2024-0413_173751](https://github.com/ermig1979/AntiDupl/assets/149738734/8aa6c718-c613-4a0b-8098-a2afb7490a5c)

**Comment by Protiguous** [comment]
Are there any related events in the Windows Event log?

**Comment by dec-mail** [comment]
ah.
well i did that, ty

And did indeed come up with these errors. which don't mean much to me, but i am wondering after that, that the prob is a new Win10 DLL?
![ShareX-2024-0420_155106](https://github.com/ermig1979/AntiDupl/assets/149738734/db88ef81-7197-4698-a63d-75965453a71c)
![ShareX-2024-0420_155023](https://github.com/ermig1979/AntiDupl/assets/149738734/14cc5f00-9718-43d6-94e6-b2975b090e8f)

i had more 
![ShareX-2024-0420_200312](https://github.com/ermig1979/AntiDupl/assets/149738734/b363c2a3-4551-47a1-a891-978d6f442281)
![ShareX-2024-0420_200246](https://github.com/ermig1979/AntiDupl/assets/149738734/99810c57-b3aa-4f43-86ae-22b288d702a0)
![ShareX-2024-0420_200231](https://github.com/ermig1979/AntiDupl/assets/149738734/75a8e1cc-ec02-4550-9565-4d27828cedf5)

**Comment by Edi61** [comment]
Hi @dec-mail,

it looks like that you copied AntiDupl to C:\Program Files(x86).
Currently program is not to be designed to be used here without any additonal efforts, since there is also no installer jet.
You can see this also in Windows Event Log, that the program has no acceas to the needed file in C:\Program Files(x86).

So for now just copy and start the program from a place where there is no security restrictions (e.g. any windows user directory)

Regards,
Erdogan

**Comment by dec-mail** [comment]
Ahhh. and tehre was i thinking i was being tidy. :-)
Ok wil try that.
Thank you.
I hopw thta works becuase for the short time i used it, it was the such a fantastic app, in the two most important ways -

1. It actually FOUND dups ;-) (and not false positives). And amazingly fast.
2. The results were displayed in a very easy to understand AND easy to use format

I might have said, i have tried MANY different photo dup apps, just recently, and over say past year+, and although there  were a few quite good, most quite bad, I was very pleasantly surprised, shocked even ;-), to see that AntiDupl was clearly the best. And, btw, i was lucky to even find it because it doesn't, as you must know, just 'pop up' when you do any search.

**Comment by dec-mail** [comment]
Update: Fixed.
Moved and updated paths and back to working perfectly

Thank you.
