### ISSUE TITLE
[poke] Libraries seems obsolete

### ISSUE THREAD

**Issue by yfdyh000** [ermig1979/AntiDupl#25]
http://www.openjpeg.org/ Latest release (v2.3.0). Faster OpenJPEG is on track.
http://ermig1979.github.io/Simd/download.html. http://ermig1979.github.io/Simd/2018.html.

**Comment by ermig1979** [comment]
Libraries have been updated.

**Comment by ermig1979** [comment]
I hope that it will be soon.
