### ISSUE TITLE
How to find out the total of found images in search path?

### ISSUE THREAD

**Issue by bsto** [ermig1979/AntiDupl#30]
How do I find out the total of found images in search path?

The number of found duplictaes is written in the lower left bottom of the status bar.
But that number is not the total number.

**Comment by ermig1979** [comment]
The total number of image is shown during search. Because it affects on time of search. Program does not show images which are not duplicated. Why does the total number of image need to show after search?

**Comment by valsaven** [comment]
@bsto I'll close it for now. If you'll have any additional questions - fell free to reopen the issue.
