### ISSUE TITLE
Не распознал картинки

### ISSUE THREAD

**Issue by Initoks** [ermig1979/AntiDupl#34]
Добрый день, я составляю себе обои на рабочий стол и когда количество картинок перевалило за 300 зная точно как минимум об одной паре картинок задался вопросом удаления пар и воспользовался вашей программой, найдя в пачке 8 совпадений именно ту пару о которой я точно знал прога не нашла, идентичное изображение и минимальные отличия по длине и высоте 1920х1080 и 1920х1200, приложил обе картинки. Предупреждаю что они правда эротического характера. Версия программы 2.3.9
[Новая папка.zip](https://github.com/ermig1979/AntiDupl/files/2042449/default.zip)

**Comment by TwiDash34** [comment]
Уберите галочку "учитывать соотношение ширены\высоты картинки", включите SSIM и поставьте 40%

**Comment by TwiDash34** [comment]
изи просто :)

**Comment by Initoks** [comment]
Ага благодарю нашел, но тогда возникает другая проблемка прога соотнесла к одинаковым совсем различные фотки.

**Comment by TwiDash34** [comment]
Ну здесь уже ничего не поделаешь, так прога написана. Такие дубликаты остается только ручками вылавливать :)

**Comment by Initoks** [comment]
Ясно, спасибо за помощь.

**Comment by heinrichI** [comment]
Да, не находится на низких порогах. Обрезанные картинки этот алгоритм не берет. Я писал программу на другом алгоритме, но она требует кучу ресурсов и для больших коллекций просто не применима. https://sourceforge.net/projects/imagecomparer/

**Comment by WonderRat** [comment]
Поставить normalized image size 16x16 - при mean square разница 11.7

**Comment by Initoks** [comment]
Попробовал, находит спс.

**Comment by nlboom** [comment]
Я перед тем как картинки в основную папку скинуть, скачала всё через AntiDupl проверяю, а потом добиваю хвосты прогоном через ImageDupeless. Он как раз хорошо с поиском таких обрезанных картинок справляется.

**Comment by valsaven** [comment]
Resolved.
