### ISSUE TITLE
Не работает на Win 10 x64

### ISSUE THREAD

**Issue by hardnyasha** [ermig1979/AntiDupl#40]
Приложение запускается в диспетчере задач и через секунду пропадает(закрывается). Что делать?

**Comment by uz-spark** [comment]
Работает, возможно у тебя проблемы с .NET Framework.

**Comment by hardnyasha** [comment]
> Работает, возможно у тебя проблемы с .NET Framework.

c другом пришли к такому же выводу. Что делать? Удалить нынешние версии версии фреймворка и установить старые что ли?

**Comment by uz-spark** [comment]
Для начала проверь что версии 2.0 и 3.5 действительно установлены, переустанови (не уверен какую из них прога использует). Не поможет - видел где-то тулзу для удаления .Net фреймворков под корень, попробуй её и переустанови заново.

**Comment by valsaven** [comment]
@hardnyasha Hi! What version do you use?

**Comment by hardnyasha** [comment]
after some windows update it all works now. i dont know which..thanks for bothering though ;D
