### ISSUE TITLE
AntiDupl 2.3.9 crashes 

### ISSUE THREAD

**Issue by PubliusHal** [ermig1979/AntiDupl#42]
Hello, I've been using AntiDupl for many years so I'm pretty familiar with its functionality. However, I have not been able to use the most recent version, 2.3.9, because it always crashes as soon as I press the 'Start Search' button; I am able to use version 2.3.8.200 with no problems. I have tried closing my anti-malware program (Malwarebytes) and have made exceptions for Windows Defender in case one of those was preventing the search, but still no luck. I'm running AntiDupl on a Win10x64 machine. Any suggestions out there? Am I being an idiot and overlooking something obvious? Thanks in advance, Scott

**Comment by valsaven** [comment]
Duplicate of #7
