### ISSUE TITLE
Please rewrote it with NET 4.5-6-7

### ISSUE THREAD

**Issue by hooddy** [ermig1979/AntiDupl#46]
Guys please rewrote AntiDupl with NET 4.5-6-7 for more versatile isage. I can use it on ARM (WinRT and ARM64).

**Comment by ermig1979** [comment]
It is not so simple. AntiDupl.NET depends on native code (x86, x64). So the using of any type of .NET framework can't do it compatible with ARM CPU.

**Comment by Thanatomanic** [comment]
@hooddy If you load up the `AntiDupl.sn` project in Visual Studio and change the target framework to anything newer (like .NET Framework 4.6), it compiles perfectly fine for me. At least, for me it does... after tweaking a few other settings that I forgot.

**Comment by hooddy** [comment]
@ermig1979 ya a lil rong. almost any project coded with net 4.5-6-7 can be recompiled with options ANY CPU and it works well under ARM. But your project compiled with NET 2.0 and I can't change it as I wrote previously. S I'm ask for a lil help.

**Comment by ermig1979** [comment]
You can fork the project and change target .NET framework. Also you need to change target CPU (x86 -> ARM) in native Visual Studio projects.

**Comment by hooddy** [comment]
@ermig1979 Я пересобрал под 4.5, но он падает.

**Comment by ermig1979** [comment]
I warned that the project contains dependencies on native x86 code. I've never checked how it works on another CPU.

**Comment by hooddy** [comment]
@ermig1979 он падает на обычной винде не на арме.

**Comment by Gigas002** [comment]
Imo it'd be better to rebuild project with .NET Core.

**Comment by Edi61** [comment]
With https://github.com/ermig1979/AntiDupl/commit/56b1c9b88b8c66450bdba32288b29b13e6fc126d 
AntiDupl is now build with .NET 6.0.
