### ISSUE TITLE
Downloaded images not detected as duplicated

### ISSUE THREAD

**Issue by Tamalero** [ermig1979/AntiDupl#47]
I recently used a tool to download a directory from a gallery full of images. The problem is, the program downloaded thumbnails and smaller sizes as well indiscriminately.

The weird part is.. If I download by hand and save them to a specified directory. The files are detected properly as duplicated by antidupl.

But If I use this particular tool and directory.. the files are not detected as duplicated by antidupl.
Even if they are identically (the only difference being the different sizes)
The images seem to be identical size wise than the originals downloaded by the browser.

Any ideas what could cause this?

The files in question: http://www.mediafire.com/folder/inly3uda6jah4/publicstuff

Screenshot of the images: 

https://prnt.sc/lwqk9s

**Comment by 1n5aN1aC** [comment]
What percent difference do you have set as considered the same?

You might have to bump that up a couple percent.  If it's 0% difference, the files would have to be literally the same to be considered.  I personally use around 5%.

**Comment by Tamalero** [comment]
I've used all the range. From 2%(the usual I use) to 20%, both modes..

all detect nothing in these particular files.
I even tried another website (twitter) and the files have the same issue.

**Comment by heinrichI** [comment]
All founded.
![image](https://user-images.githubusercontent.com/7752557/50328739-be7baa00-050d-11e9-9cee-0531a4c94699.png)

**Comment by Tamalero** [comment]
Interesting, could be a permissions issue? or image database issue?

**Comment by heinrichI** [comment]
I do not know.

**Comment by valsaven** [comment]
Looks like everything's working correctly.
@Tamalero I'll close it for now. If you'll find additional details - just reopen the issue.
