### ISSUE TITLE
AntiDupl алгоритм

### ISSUE THREAD

**Issue by tovchik** [ermig1979/AntiDupl#50]
Добрый день!

Большое спасибо Вам за отличную программу AntiDupl!

Я коллекционирую обои с девушками (приличными) и набрал их около 100 тыс.
Много лет назад я проводил сравнение разных программ для поиска дублей и Ваша программа оказалась лучшей.
С тех пор пользуюсь только ей. Сейчас стоит AntiDupl.NET-2.3.9.
Дубли постоянно проверяю по обоим алгоритмам, по среднеквадратичному в диапазоне 5-10%, по SSIM 20-24%.
Но недавно проверил свою коллекцию у приятеля, он на Ubuntu использует для своих проверок на дубли программу findimagedupes.
И оказалось, что в моей коллекции нашлось более 4000 невыловленных дублей.
При исследовании оказалось, что не ловятся картинки, которые отличаются тем, что у них обрезан верх и низ.
Проверял в AntiDupl.NET при максимальных настройках обоих алгоритмов (по среднеквадратичному 15%, по SSIM 50%).
Для демонстрации прилагаю несколько картинок.

Если Вы собираетесь и дальше совершенствовать свою отличную программу, то предлагаю как-то учесть эту ситуацию.
Например, к уже существующим двум алгоритмам добавить третий, как их ищет findimagedupes или каким-то другим, удобным Вам способом.

Если интересно, то их алгоритм в мануале изложен так:
findimagedupes compares a list of files for visual similarity.
To calculate an image fingerprint:
  1) Read image.
  2) Resample to 160x160 to standardize size.
  3) Grayscale by reducing saturation.
  4) Blur a lot to get rid of noise.
  5) Normalize to spread out intensity as much as possible.
  6) Equalize to make image as contrasty as possible.
  7) Resample again down to 16x16.
  8) Reduce to 1bpp.
  9) The fingerprint is this raw image data.
To compare two images for similarity:
  1) Take fingerprint pairs and xor them.
  2) Compute the percentage of 1 bits in the result.
  3) If percentage exceeds threshold, declare files to be similar.
Я в этом не очень разбираюсь, но Вам может что и подскажет.

С уважением,
  Ваш преданный пользователь

P.S. Извините за многословность
 
![1-1920x1080](https://user-images.githubusercontent.com/46869050/51444235-5c79b480-1d06-11e9-99b8-1910f9d33cb5.jpg)
![1-1920x1200](https://user-images.githubusercontent.com/46869050/51444236-5c79b480-1d06-11e9-891a-4e68901ebf49.jpg)
![2-1920x1080](https://user-images.githubusercontent.com/46869050/51444237-5c79b480-1d06-11e9-8748-21d74d000afb.jpg)
![2-1920x1280](https://user-images.githubusercontent.com/46869050/51444238-5c79b480-1d06-11e9-8b80-dfe37d5dd007.jpg)
![3-1920x1080](https://user-images.githubusercontent.com/46869050/51444239-5d124b00-1d06-11e9-936b-977a0a210312.jpg)
![3-1920x1200](https://user-images.githubusercontent.com/46869050/51444240-5d124b00-1d06-11e9-97e3-300d79cf5225.jpg)

**Comment by heinrichI** [comment]
> findimagedupes

А долго работает этот findimagedupes?
И может ли найти такие дубли?
![default](https://user-images.githubusercontent.com/7752557/51456947-eeb2a480-1d68-11e9-9c6e-b719fcb7143a.jpg)
![_2](https://user-images.githubusercontent.com/7752557/51456948-eeb2a480-1d68-11e9-88cb-79d0eac8f840.jpg)

При таких настройках все ваши девушки нашлись. 
![image](https://user-images.githubusercontent.com/7752557/51457030-376a5d80-1d69-11e9-9aaf-17de19e3c46d.png)

У меня проблема в последние годы не чтобы найти дубликаты а чтобы автоматических удалить худший. Я больше 100 не могу руками. А ведь их тысячи находятся.

**Comment by heinrichI** [comment]
Не смог собрать findimagedupes под windows. Проверьте найдет ли эти изображения. И приемлемое ли количество ложных дубликатов.
![20120613-tom-cruise-syuting-film-science-fiction-01](https://user-images.githubusercontent.com/7752557/51462846-16126d00-1d7b-11e9-8d24-182c521dd2fe.jpg)
![20120613-tom-cruise-syuting-film-science-fiction-02](https://user-images.githubusercontent.com/7752557/51462847-16126d00-1d7b-11e9-934b-2bc0144ecb03.jpg)
![emma stone katharine mcphee kat dennings anna faris rumer willis the house bunny](https://user-images.githubusercontent.com/7752557/51462849-16126d00-1d7b-11e9-9edf-602e91d6b8e2.jpg)
![emma stone](https://user-images.githubusercontent.com/7752557/51462851-16ab0380-1d7b-11e9-80ca-2f178a5df261.jpg)

**Comment by tovchik** [comment]
Спасибо за ответ!

Дважды спасибо за то, что ткнули носом в Опции - я их не замечал и никогда не использовал.
Правда на закладке "Дополнительные" у меня все как у Вас, но все дело оказалось на закладке "Сравнение". Там по умолчанию стоит галочка у пункта "Учитывать соотношение ширины/высоты картинок". Достаточно было ее убрать и все дубли стали прекрасно находиться. Еще раз спасибо.
Так что ихняя findimagedupes уже не актуальна ;)

Но отвечу и про нее. 
1) На 96 тыс. картинок она создавала первичную базу и искала дубли 2.5-3.0 часа на компе с процессором  "Core 2 Duo  E8500 @ 3.16GHz × 2" и 8Гб ОП.
2) Она консольная и в результате выдает список груп с именами похожих (с ее точки зрения картинок). Степень похожести картинок там там регулируется ключиком "threshold", который описывается так:
  -t, --threshold=AMOUNT
            Use AMOUNT as threshold of similarity. Append "%" to give a
            percentage or "b" for bits. For backwards compatibility, a
            number with no unit is treated as a percentage. Percentage is
            the minimum required for a match; bits is the maximum that may
            differ: bits=floor(2.56(100-percent))
            A fractional part may be given but it is only accurate to
            100/256 (0.390625) for percentage and it is meaningless for
            "bits". Default is "90%" ("25b") if not specified.
Значение по умолчанию 90% мы не меняли.

В моем случае она выдала:
- около 4 тыс. групп дублей с двумя-тремя картинками в каждой группе (с разной высотой), что действительно является дублями;
- около сотни  групп с 4-8 картинками в каждой группе, там в каждой группе к двум-трем правильных дублей примешались по 5-6 шт. ложных срабатываний;
- несколько тысяч (!) групп с количеством картинок по 10-30 штук в каждой. Так как я свою коллекцию регулярно чищу, то  проверив несколько десятков таких групп и не найдя там дублей вообще, эти группы отбросил как  100% ложные срабатывания.
3) Указанные Вами три пары картинок она не ловит на стандартной чувствительности 90% .
Начиная с 82% ловится первая пара  (где Entertainment),  начиная с 66% также ловится третья пара (с девушками), на  56% ловятся все три пары, а начиная с 55% и ниже ВСЕ шесть картинок считаются дублями друг к другу.

По поводу худших картинок.
Я подбираю (и конвертирую) все свои обои к 1920x(1080-1440) до поиска дублей. 
Ваш текущий алгоритм автоматического удаления дублей меня устраивает полностью.
Вначале сбора коллекции я довольно тщательно глазами выбирал лучшие, поэтому сейчас, то что остается после вашего автоматического удаления обрабатываю по принципу: позже появился у меня - значит хуже.

Так что мой вопрос, поднятый в топике, считаю полностью закрытым.
Еще раз спасибо за Вашу программу,

с уважением, 
   tovchik.
