### ISSUE TITLE
SUGGESTION: Preferred folder

### ISSUE THREAD

**Issue by tritrek** [ermig1979/AntiDupl#51]
Hi,
first: thank you for this wonderful and simple software! Awesome and very helpful.
I'd have one suggestion though: it would be very useful to have a 'preferred folder' - so that when it looks up files from a number of folders, I could set a preferred folder so the other folder would be preferred to get deleted in case the files are 100% identical. 
A very specific case of mine:
I have a NAS where I'm storing my photos from my cameras, but also from my and my wife's phone. I get those pics downloaded from online repositories (iCould and GDrive) every now and then then I import them. The problem is, I have my system of naming my imported files so sometimes I have duplicates (original name VS renamed file). Now, I download files and want to import them but Lightroom doesn't differentiate between two files of different names but same image data. SO this preferred folder would be set to my NAS imported folder so when I compare the files already imported and the one to be imported, the program would automatically mark the file to be deleted saying "hey man, you already have this in your PREFERRED FOLDER, you can delete it.
Does it make any sense?
Thanks :)

**Comment by user3430534** [comment]
I might have misunderstood your request but isn't there something like that already implemented? Valid and Delete tabs in Paths window seem like what you looking for.
And if you want to delete a file only if it is binary equal with just name being different, take a look at CloneSpy it might suit better for this purpose.

**Comment by valsaven** [comment]
@tritrek Did it help you?
