### ISSUE TITLE
export report

### ISSUE THREAD

**Issue by marcob71** [ermig1979/AntiDupl#53]
Is it possible to implement an export report about results?P
It may be in xml or csv.

thank you

**Comment by ermig1979** [comment]
https://ermig1979.github.io/AntiDupl/data/help/english/index.html?page=faq.html

_How do I get a list of the results in text format?_

Select list of results with using key combination Ctrl-A. Copy to clipboard with using key combination Ctrl-C. Then copy it into your text file with using key combination Ctrl-V.

**Comment by valsaven** [comment]
Resolved
