### ISSUE TITLE
How to search a single folder, and not subdirectories?

### ISSUE THREAD

**Issue by JohnTravolski** [ermig1979/AntiDupl#54]
The documentation says:

By default, images are searched for the same in all subdirectories, but the user can change the corresponding parameter Search - Search in subdirectories of the search settings.

However, when I go to the search tab:

https://i.imgur.com/igDOvmi.png

No such option is anywhere to be seen.  Same with the "Search" context menu:

https://i.imgur.com/tvn9NTi.png

How can I tell AntiDupl to not search subdirectories?  I'm using this version:

https://i.imgur.com/3VugUzQ.png

**Comment by heinrichI** [comment]
![image](https://user-images.githubusercontent.com/7752557/55216814-2f221900-5217-11e9-8384-d6692812964d.png)

**Comment by JohnTravolski** [comment]
Thank you, I understand now.

**Comment by valsaven** [comment]
Resolved :)
