### ISSUE TITLE
Соседние кадры

### ISSUE THREAD

**Issue by doctorkhv** [ermig1979/AntiDupl#58]
Здравствуйте! Как в последовательности из ~ 100 000 изображений (кадров) удалить только соседние (смежные) кадры-дубликаты? Я не программист, но наверняка можно, к Вашей замечательной программе добавить .ps1 .bat. С уважением.

**Comment by heinrichI** [comment]
Что значит соседние?

**Comment by doctorkhv** [comment]
Кадры расположенные рядом. Например 77 - 78, но не 77- 79.

**Comment by heinrichI** [comment]
Сейчас такой функции нет. Если сформулируйте могу попробовать добавить. 
Вот нашлось 3 дубликата. 77, 78, 79. Как определить по свойствам изображения какая лучше? Как определить по названию файлов какая лучше? 
То есть удалить 77, и 78. Или 78 и 79? Как определить какие файлы откинуть?

**Comment by doctorkhv** [comment]
При записи старых фильмов, для приведения в стандартную частоту 23,976 или 25 кадров в секунду, добавлялись кадры дубли, но так как удалять артефакты (пятна, царапины) было лень, то эти артефакты передавались и кадрам дубликатам. Иногда в определенной последовательности (например каждый пятый), иногда хаотично. Лучше бороться с артефактами, когда они только на одном кадре. В Avisynth есть возможность обнаружить эти дубликаты и удалить, при помощи DeDup http://akuvian.org/src/avisynth/dedup/dedup.txt но я хочу попытаться удалить эти кадры временно, сделать секвенцию (последовательность) кадров с пропущенными (временно удаленными, лучше конечно перемещенные в другую папку).  Затем, удалить артефакты в секвенции с пропущенными кадрами, потом добавить в секвенцию (временно удаленные) и обработать еще раз. 
Покадрово просмотрите небольшой видеофрагмент  и Вы увидите кадры-дубликаты с артефактами, которые и нужно временно удалить  https://drive.google.com/open?id=1GSdAlTdGxSSbWn9sz-KTMQXvSNPcQfqe или папку https://drive.google.com/open?id=1k_9_5GIt70uyKgit44wYqmvCLTKkz0fe со 100 кадрами (их 511, но для экономии Вашего времени сделал 100) этого видеофрагмента.

**Comment by heinrichI** [comment]
Это применено понятно. Но алгоритм не понятен. Перенести в папку это понятная функция. На моем примере из 77, 78 и 90 какие надо перенести файлы?

**Comment by doctorkhv** [comment]
Только 78.

**Comment by heinrichI** [comment]
Значит получается нужна функция фильтровки группы результатов которая будет оставлять только файлы с соседними номерами. И функция переноса в папку. Пишите на jeronimo73@gmail.com

**Comment by doctorkhv** [comment]
Спасибо! Удаление кадров-дубликатов не улучшает видеобработку. Поэтому я с этим пока заниматься не буду. Еще раз СПАСИБО!

**Comment by nxrighthere** [comment]
Я бы попутно к этому issue хотел бы предложить ещё функцию игнорирования соседних файлов в указанном диапазоне. Сейчас программа определяет много соседних дубликатов которые на самом деле просто разновидности одного и того же изображения и располагаются например: (48).jpg, (49).jpg, (50).jpg и т.д. Сейчас руками добавляю в исключения такие цепочки изображений, автоматизация помогла бы.

**Comment by valsaven** [comment]
Resolved!

@nxrighthere You can create a new issue with this request :)
