### ISSUE TITLE
Problems with some images

### ISSUE THREAD

**Issue by jmmartininfoadex** [ermig1979/AntiDupl#64]
I'm using the library and is working fine for almost every case. However, I've a list of images with a high similarity (duplicates for a human eye), and I'm not able to set up the application in order to get a right list of duplicates images. 

For these 96 files, the application always ends the process very quick, and no item is showed in the list. Other images in the same folder works fine and the program returns apropiate results.
Is it possible to send some of this examples just to analyze them, and if it's tha case, contribute to resolve some bug?

Thanks in advance and many thanks for your great work.

[images in gif format.zip](https://github.com/ermig1979/AntiDupl/files/3319710/images.in.gif.format.zip)
[images in png.zip](https://github.com/ermig1979/AntiDupl/files/3319711/images.in.png.zip)

**Comment by heinrichI** [comment]
Check minimal image width/height
![image](https://user-images.githubusercontent.com/7752557/60253193-38289200-98bb-11e9-8812-f4efba9277e8.png)

**Comment by jmmartininfoadex** [comment]
It worked. Thanks!
