### ISSUE TITLE
Give it a try, I search for no duplicate results, unknown reason

### ISSUE THREAD

**Issue by sls463** [ermig1979/AntiDupl#68]
[TEST.zip](https://github.com/ermig1979/AntiDupl/files/3773478/TEST.zip)

**Comment by heinrichI** [comment]
Set search in hidden files.
![image](https://user-images.githubusercontent.com/7752557/67660077-cd18c600-f955-11e9-965a-aaad8f0d5922.png)

**Comment by sls463** [comment]
Thank you,&nbsp;Please take a look at the following questions,&nbsp;Added explanation Cause
https://github.com/ermig1979/AntiDupl/issues/39




------------------&nbsp;原始邮件&nbsp;------------------
发件人:&nbsp;"heinrichI"<notifications@github.com&gt;;
发送时间:&nbsp;2019年10月28日(星期一) 下午3:38
收件人:&nbsp;"ermig1979/AntiDupl"<AntiDupl@noreply.github.com&gt;;
抄送:&nbsp;"苏生"<262305727@qq.com&gt;;"Author"<author@noreply.github.com&gt;;
主题:&nbsp;Re: [ermig1979/AntiDupl] Give it a try, I search for no duplicate results, unknown reason (#68)




Set search in hidden files.
