### ISSUE TITLE
не работает версия 2.3.9

### ISSUE THREAD

**Issue by Vilmodao** [ermig1979/AntiDupl#7]
Падает программа после нажатия на кнопку start search.
![screenshot_2018_01_16_at_21_01_58](https://user-images.githubusercontent.com/11928504/35005073-4c4f462c-fb03-11e7-84e6-a88bd76794fc.png)
В папке, в которой производится поиск, должна быть хоть одна картинка (проверял png, jpg, gif). Если в папке нет картинок, то программа не падает.

Замусоренная Windows 8.1 x64 
Только что скаченная AntiDupl.NET-2.3.9 
Версия 2.3.8 работает без проблем.
Наверное, что-то в моей системе, но я даже не представляю куда смотреть.

**Comment by ermig1979** [comment]
Какие-то специфические настройки или все по умолчанию?

**Comment by Vilmodao** [comment]
Настройки не меняю. Но, похоже, картинки имеют значение.
**Подробнее:**
Все делаю на рабочем столе. 
Распаковываю дистрибутив в Desktop\AntiDupl.NET-2.3.9
Рядом отдельная папка Desktop\temp, ее будет анализировать программа.
Запускаю AntiDupl, жму иконку paths, там выделяю строку, жму change, указываю на Desktop\temp, закрываю программу чтобы она нормально запомнила путь. Вот и все настройки.
**Теперь самое интересное:**
Запускаю AntiDupl, нажимаю иконку start search. В большинстве случаев программа падает если в папке temp есть картинки, НО не всегда. 
Я прикрепил архив с картинками. Файлы с названием "a" не обваливают программу. Файлы типа "b" — обваливают. Если в анализируемой папке есть хоть один файл "b" — получаю скрин из моего первого сообщения. Файлы типа "а" реже встречаются на моем компе. В остальном, я не понял чем они отличаются.
Файлы PNG я получил из соответствующих JPG прогнав их через фотошоп (quick export). 
[Desktop.zip](https://github.com/ermig1979/AntiDupl/files/1636976/Desktop.zip)
ну пока так...

**Comment by ermig1979** [comment]
Проверил. И те, и те работают нормально у меня на компе. 
Исправил мелкий баг, но он скорее всего не связан с этой проблемой.

**Comment by Vilmodao** [comment]
Странно. У меня все повторяется даже на практически чистой виртуалке.
![screenshot_2018_01_17_at_15_39_40](https://user-images.githubusercontent.com/11928504/35043620-5435a980-fb9e-11e7-9716-01bdba9a53de.png)

Подробности ошибки если это поможет:

```
Описание:
  Stopped working

Сигнатура проблемы:
  Имя события проблемы:	APPCRASH
  Application Name:	AntiDupl.NET.exe
  Application Version:	2.3.9.0
  Application Timestamp:	5a5467a1
  Fault Module Name:	AntiDupl64.dll
  Fault Module Version:	0.0.0.0
  Fault Module Timestamp:	5a5467f2
  Exception Code:	c0000005
  Exception Offset:	00000000000d06d9
  Версия ОС:	6.3.9600.2.0.0.256.4
  Код языка:	1049
```

Может быть позже, если будет время, попробую на других виртуалках.

**Comment by Saere** [comment]
Такая же фигня на 7 винде. Правда, у меня и 2.3.8 падает на поиске.  Настройки по умолчанию, антивирус отключила. 
 попробовала на тех же папках 2.3.7 - работает

**Comment by nikolay-borzov** [comment]
Аналогичное поведение - Win 10 x64

**Comment by temnyuk** [comment]
Подтверждаю. Win 7 x32
2.3.8 - работает.
2.3.9 - вылетает почти сразу при поиске.
Файлов около 5 тысяч в трех папках.

**Comment by MarkoniYA** [comment]
Подтверждаю. Win 7 x32 не замусоренная. Только установленная с обновлениями.
2.3.8 - работает.
2.3.9 - вылетает сразу после начала поиска.

**Comment by PalmtopTiger** [comment]
Тоже 2.3.9 вылетает при поиске.
Может быть связано с тем, что старые процессоры не поддерживают новые инструкции, вроде SSE4.
ОС: Windows 7 SP1 x64
CPU: AMD Phenom II X6 1100T

**Comment by ermig1979** [comment]
Phenom II поддерживает SSE4. Впрочем тут проблема не в этом - Simd проверяет наличие у процессора специфических инструкций переди их использованием.

**Comment by PalmtopTiger** [comment]
Phenom II поддерживает SSE4a. Это не SSE4.
<a href="https://user-images.githubusercontent.com/3754317/35843298-e46dddec-0b39-11e8-91b9-bc7f4bb4d110.png"><img src="https://user-images.githubusercontent.com/3754317/35843298-e46dddec-0b39-11e8-91b9-bc7f4bb4d110.png" height="100" width="99" ></a>
Не буду настаивать, что причина именно в этом, но сейчас все 64-битные программы поголовно начали падать на феномах и Core 2 Duo после перехода их авторов на новую студию.
2.3.8 была собрана 2008-й студией, а 2.3.9, видимо, 2015 или 2017.
В любом случае, спасибо за отличную программу. С уважением.

**Comment by ermig1979** [comment]
У меня дома и на работе Windows 10. CPU тоже довольно новые. Не могу воспроизвести проблему. А без этого ее не решить.

**Comment by heinrichI** [comment]
У меня дома старый Core 2 Duo, в выходные могу проверить релизную версию.

**Comment by PhonyWelder** [comment]
Если я правильно нашел место, то это ```.00000001`800D06D9: 660FDB440FE0                   pand        xmm0,[rdi][rcx][-020]``` - SSE2: http://www.felixcloutier.com/x86/PAND.xml
c0000005 - access violation.

У меня не падает; W7U SP1 x64, AMD A8-9600, 16GB

**Comment by Vilmodao** [comment]
У меня тоже Phenom II, если это важно.

**Comment by heinrichI** [comment]
Проверил на Core 2 Duo - работает версия 2.3.9.

**Comment by valsaven** [comment]
Same with AMD Phenom(tm) II X6 1090T and 2.3.9 version.
![debug](https://user-images.githubusercontent.com/16094011/36358631-6fb86bbe-1522-11e8-9f51-bdc9774cb3a2.PNG)
2.3.8 works great.

**Comment by PalmtopTiger** [comment]
Исходя из того, что на Core 2 Duo и AMD A8 не падает, а на Phenom II - падает, дело в SSSE3 или SSE4.1.

**Comment by PhonyWelder** [comment]
```
Specification		AMD A8-9600 RADEON R7, 10 COMPUTE CORES 4C+6G  
Instructions sets	MMX (+), SSE, SSE2, SSE3, SSSE3, SSE4.1, SSE4.2, SSE4A, x86-64, AMD-V, AES, AVX, AVX2, XOP, FMA3, FMA4
```

**Comment by GDStaff** [comment]
Windows 7 x64
AntiDupl.NET-2.3.9 - падает при поиске
AntiDupl.NET-2.3.8 - все отлично

**Comment by ermig1979** [comment]
Не актуально в связи с выходом следующей версии.
