### ISSUE TITLE
Preparation to Antidupl.NET-2.3.10

### ISSUE THREAD

**Issue by ermig1979** [ermig1979/AntiDupl#70]
Add support of libjpeg-turbo. It needs to improve performance of loading of jpeg images.

Key release features:

1. Add webp format.
2. Improve performance of jpeg.

Do I forget something?

**Comment by ermig1979** [comment]
It will be amazing if anybody test this version: [AntiDupl.NET-2.3.10d.zip](https://github.com/ermig1979/AntiDupl/files/3846007/AntiDupl.NET-2.3.10d.zip)

I am waiting for reviews!

**Comment by KoalaBear84** [comment]
Tested it with 37K files (12.1GB), only JPG though. Worked without problems, found 1274 groups at the default 5%.

Is there a way to group more than 2 similar images? Something there are multiple groups of the same picture. Thanks!

**Comment by ermig1979** [comment]
> Is there a way to group more than 2 similar images? Something there are multiple groups of the same picture. Thanks!

You can sort result by second column **Group**.

**Comment by KoalaBear84** [comment]
Thanks, works a lot better when having (too) many duplicates!

**Comment by heinrichI** [comment]
> Tested it with 37K files (12.1GB), only JPG though. Worked without problems, found 1274 groups at the default 5%.
It is faster them previous version?

**Comment by KoalaBear84** [comment]
Hmm. No. Should be according to point 2.

AntiDupl 2.3.9    12 minutes and 30 seconds
AntiDupl 2.3.10  12 minutes and 44 seconds

**Comment by ermig1979** [comment]
It seems we need to perform performance testing.

**Comment by ermig1979** [comment]
I added option to switch on/off of libjpeg-turbo.
Also I added search performance log (it is stored in ./user/performance.txt).
This a new version:

[AntiDupl.NET-2.3.10.4.zip](https://github.com/ermig1979/AntiDupl/files/3851702/AntiDupl.NET-2.3.10.4.zip)

The result of comparison on SSD:

    ---------------------------------------------------------------
    Search start time: 15.11.2019 16:34:19
    Elapsed time: 00:01:01.2724435
    Found 11,2 GB of 32753 images in 27 folders.
    Processed 32753 images.
    Found 0 defects and 5 duples.
    Used 10 load and 10 compare theads.
    Use image database: False.
    Use libjpeg-turbo: True.
    ---------------------------------------------------------------
    Search start time: 15.11.2019 16:35:31
    Elapsed time: 00:01:17.8300273
    Found 11,2 GB of 32753 images in 27 folders.
    Processed 32753 images.
    Found 0 defects and 5 duples.
    Used 10 load and 10 compare theads.
    Use image database: False.
    Use libjpeg-turbo: False.

Conclusion: libjpeg-turbo gives gain about 25-30% to compare to standard Windows solution.
The gain is reached if we don use image database and if we use fast drive (SSD).
Otherwise the gain is not obvious.

**Comment by ermig1979** [comment]
I hope that can fix crash during search (issue 72):

[AntiDupl.NET-2.3.10.5.zip](https://github.com/ermig1979/AntiDupl/files/3891474/AntiDupl.NET-2.3.10.5.zip)

It will be wonderful if anybody performs independent test.

**Comment by KoalaBear84** [comment]
#66 (WebP) Could be closed when this version is released

**Comment by ProzacMan** [comment]
Using version 2.3.10.5 the application just closes shortly after starting a scan. This happens with multiple different groups of folders. No error message, I can't find a log file.

**Comment by celan69** [comment]
I had similar problems with a version I compiled myself with VS 2019. After removing the "WholeProgramOptimization" entries from Prop.props, it worked. And by the way, thanks for your work, Ihar!

**Comment by ermig1979** [comment]
> I had similar problems with a version I compiled myself with VS 2019. After removing the "WholeProgramOptimization" entries from Prop.props, it worked. And by the way, thanks for your work, Ihar!

Did you remove this options:
      <WholeProgramOptimization>false</WholeProgramOptimization>
from Prop.props and it solved crashes?

**Comment by celan69** [comment]
I removed <WholeProgramOptimization Condition="'$(Configuration)'=='Release'">true</WholeProgramOptimization> and <WholeProgramOptimization>false</WholeProgramOptimization>. I am new to Visual Studio (i am coming from the Unix world) so this whole build configuration stuff in VS is not quite clear to me.

**Comment by celan69** [comment]
Aah, I see. The first line was introduced by upgrading the Solution/Project to Visual Studio 2019 and the Platform Tool set v142.

**Comment by ermig1979** [comment]
Ok. I will test the program with this changes.

**Comment by ermig1979** [comment]
I rebuilt the project with changed options. I note that the size of binary files increased significantly. The application works fine (at my computer). But I would to wait for independent confirmation.

[AntiDupl.NET-2.3.10.6.zip](https://github.com/ermig1979/AntiDupl/files/4243382/AntiDupl.NET-2.3.10.6.zip)

**Comment by ProzacMan** [comment]
That fixed it for me, I was able to scan a folder with 13,000 images that failed before. Thanks a ton for looking at it everyone!

**Comment by ermig1979** [comment]
Hello everyone! 
If there is no troubles then can I start to prepare release?

**Comment by ProzacMan** [comment]
I have been running it all day and no crashes works great!

**Comment by TwiDash34** [comment]
Последняя версия работает отлично. Но есть одна проблема, это фоновый режим. Если его использовать, то через несколько минут программа просто молча закрывается. Это дико бесит, приходится не использовать этот режим. Будет здорово если поправите ;)
