### ISSUE TITLE
Медленное удаление дубликатов

### ISSUE THREAD

**Issue by FlashAJ** [ermig1979/AntiDupl#77]
Почему Ваша программа удаляет картинки дольше, чем сканирует?

**Comment by ermig1979** [comment]
Есть в программе такая функция отмены удаления картинок.
Если ее отменить: [Опции - Дополнительные - Размер очереди отмены - 0](https://ermig1979.github.io/AntiDupl/data/help/russian/index.html?page=options.html), то все будет работать быстро.

_Размер очереди отмены - данный параметр регулирует максимальное количество действий, которые пользователь может отменить подряд. Данный параметр может изменяться в диапазоне от 0 до 16. По умолчанию имеет значение 10. Отметим, что для возможности отмены операции пользователя требуется сохранять промежуточное состояние программы, и произведенные данной операцией изменения. Так, при операции удаления изображений, происходит не удаление изображений, а их скрытие и переименование (полученные скрытые временные файлы удаляются позже). Естественно, что эти операции требуют дополнительных ресурсов и могут замедлять работу программы. При малом значении размера очереди отмены происходит экономия ресурсов программы. В частности, при нулевом значении этого параметра происходит прямое удаление файлов без их переименования и скрытия, что ускоряет работу программы._

**Comment by FlashAJ** [comment]
Спасибо.
