### ISSUE TITLE
Give it a try, I search for no duplicate results, unknown reason

### ISSUE THREAD

**Issue by sls463** [ermig1979/AntiDupl#78]
[TEST2.zip](https://github.com/ermig1979/AntiDupl/files/4197273/TEST2.zip)

**Comment by ermig1979** [comment]
I have checked. It works. I would you to check the folder properties (maybe it is hidden or system).

**Comment by sls463** [comment]
![2](https://user-images.githubusercontent.com/41649803/74419972-a8554980-4e85-11ea-8825-164baa2bce32.jpg)








![Uploading 1.jpg…]()

**Comment by sls463** [comment]
ME Test Options: AntiDupl.NET v2.3.8 & AntiDupl.NET v2.3.10-alpha-v4 
![1](https://user-images.githubusercontent.com/41649803/74420021-be630a00-4e85-11ea-9604-bb6ecda4a24f.jpg)
![2](https://user-images.githubusercontent.com/41649803/74420025-bf943700-4e85-11ea-9e1d-31bade4c6e5b.jpg)
![3](https://user-images.githubusercontent.com/41649803/74420042-c91d9f00-4e85-11ea-91c8-518e77547ef6.jpg)
![4](https://user-images.githubusercontent.com/41649803/74420048-cae76280-4e85-11ea-9b69-7de1e1406ea1.jpg)
![5](https://user-images.githubusercontent.com/41649803/74420054-ccb12600-4e85-11ea-93c5-40124465331e.jpg)
![7](https://user-images.githubusercontent.com/41649803/74420066-d044ad00-4e85-11ea-9e84-9cda127a9572.jpg)
![8](https://user-images.githubusercontent.com/41649803/74420073-d20e7080-4e85-11ea-8105-e8a7ea4da26e.jpg)
![9](https://user-images.githubusercontent.com/41649803/74420077-d3d83400-4e85-11ea-8c78-a205b835b7e6.jpg)

**Comment by ermig1979** [comment]
Could you also check Path options?

**Comment by sls463** [comment]
![a1](https://user-images.githubusercontent.com/41649803/74421765-84dfce00-4e88-11ea-9667-3b72260892c0.jpg)
![a2](https://user-images.githubusercontent.com/41649803/74421777-89a48200-4e88-11ea-8d27-afeb32ce52da.jpg)
![a3](https://user-images.githubusercontent.com/41649803/74421785-8b6e4580-4e88-11ea-998e-75ddb348c8af.jpg)
![a4](https://user-images.githubusercontent.com/41649803/74421791-8c9f7280-4e88-11ea-844b-d44bfccbb26a.jpg)

**Comment by ermig1979** [comment]
It is strange. The program options and paths are looked good.

**Comment by sls463** [comment]
![9](https://user-images.githubusercontent.com/41649803/74423348-151f1280-4e8b-11ea-93fd-31d65dc6a46e.jpg)
“Authenticated Users” This is what I added. None before. Is this the reason?

**Comment by sls463** [comment]
AntiDupl.NET v2.3.8 --- Search for no duplicate results
Update to AntiDupl.NET v2.3.10 --- Problem solved
