### ISSUE TITLE
Search doesn't check all files

### ISSUE THREAD

**Issue by Prinz23** [ermig1979/AntiDupl#80]
When starting a Search of a folder with subfolders that contain around 444000 images the search simply stops around 140000 scanned files and jumps to finished.

There is not error message. 

Is there any way to find out at which file this fails?

I tried AntiDupl.NET v2.3.9 and complied the current source. Happens with both.

**Comment by ermig1979** [comment]
I have an assumption:

**Options -> Advanced options -> Maximal count of results** - this parameter controls the maximum number of results that a program can be found in one search. For example, if during the search program will be achieved this the number of results, the search will be automatically terminated. This restriction is useful to save program resources allocated to the graphical representation of the results list. By default, this value is 100000.

[https://ermig1979.github.io/AntiDupl/data/help/english/index.html?page=options.html](url)

**Comment by Prinz23** [comment]
Yes that was the problem. I changed the setting to 1.000.000 and now all is working. Totally overlooked that setting in advanced. 

Thanks for the help and the useful program.
