### ISSUE TITLE
Господа авторы, куда вам донатить деньгами? Нигде не нашел. 

### ISSUE THREAD

**Issue by Igor12011980** [ermig1979/AntiDupl#86]

**Comment by heinrichI** [comment]
А вам с целью добавления определенной функции или просто благодарность?

**Comment by Igor12011980** [comment]
Просто в благодарность.

**Comment by ermig1979** [comment]
Были раньше реквизиты. Так за 18 лет накапало аж 37 $. Не знаю даже, что делать со всем этим богатством!

**Comment by Igor12011980** [comment]
Ну, сейчас есть сервисы, которые позволяют по одному клику деньги послать. 18 лет назад нужно было гораздо больше телодвижений. Большинство людей не хотят донатить не потому, что им 2-5 доллара жалко, а потому, что лень. В любом случае, благодарю за ответ.
