### ISSUE TITLE
Dev: which branch is actively developed?

### ISSUE THREAD

**Issue by yfdyh000** [ermig1979/AntiDupl#88]
.NET? WPF? or parallel?

**Comment by ermig1979** [comment]
I think master contains last changes.

**Comment by yfdyh000** [comment]
To be precise, the WinForm development still active or will it be deprecated? I see the WPF development, but failed to compile it.

**Comment by ermig1979** [comment]
[Dmitry](https://github.com/heinrichI) tries to develop WPF version, but it still not works. So it is better start from WinForm versions.

**Comment by yfdyh000** [comment]
Thanks for your answers.
