### ISSUE TITLE
How to edit the GUI

### ISSUE THREAD

**Issue by fiyerowei** [ermig1979/AntiDupl#90]
Sorry, I am a beginner of .Net programming.
I download the VC 2019 and finish all the rebuild process is successful. However I try to edit the UI, for example the file 
AntiDupl/src/AntiDupl/AntiDupl.NET/Form/MainForm.cs

But there’s always some errors and cannot display the components When I  want to check in design tool. Messages such as cannot find the style “AntiDupk.Net.InitFactory+Layout”
“ AntiDupk.Net.AboutProgramPanel”

Did i lost any files or should I install something for normally edit the .cs file by design tool?

**Comment by yfdyh000** [comment]
Duplication of #87?
