### ISSUE TITLE
Очень похожие непохожи

### ISSUE THREAD

**Issue by Oleg-Motus** [ermig1979/AntiDupl#92]
Использовал AntiDupl 2.3.10. Две приложенных фотографии программа определила непохожими при любом методе сравнения и любой степени. Что делать?
![2020-04-28-0010-6](https://user-images.githubusercontent.com/41068282/81169847-3ed76980-8fa2-11ea-9473-fff718f62d4c.jpg)
![2020-04-28-0014-4](https://user-images.githubusercontent.com/41068282/81169852-40089680-8fa2-11ea-9082-81750a6e9397.jpg)

**Comment by ermig1979** [comment]
Известный баг - AntiDupl плохо работает с обрезанными картинками.

**Comment by Oleg-Motus** [comment]
Нашел сочетание параметров Compare:
![Буфер обмена-1](https://user-images.githubusercontent.com/41068282/198821480-da9d678e-4135-4cf1-a844-eb14f6267ce0.jpg)
