### ISSUE TITLE
Падает при сканировании папки

### ISSUE THREAD

**Issue by Slavian2** [ermig1979/AntiDupl#95]
Добрый день.

Программа падает примерно на 123-м файле из 430к изображений в папке. Падает без сообщений об ошибке. Настройки сбрасывается.

Полагаю, что падает из-за парсинга файла. Есть ли возможность включить дебажный режим или как-то понять, что идёт не так? Могу записать видео, если потребуется.

Первый прогон программы на 100к результатов прошёл хорошо.

**Comment by ermig1979** [comment]
Было бы не плохо понять на каком файле падает. И прислать его сюда.

**Comment by Slavian2** [comment]
В папке >400k файлов, а в логе выполнения названия быстро проскакивают. У меня не стоит дома студия, могу скачать пиратку, но буду благодарен, если вы просто соберёте Debug сборку и передадите мне. Я тогда верну дамп и логи.

**Comment by ermig1979** [comment]
64 bit?

**Comment by Slavian2** [comment]
Да

**Comment by ermig1979** [comment]
Попробуйте [скачать](https://drive.google.com/file/d/1p0rZKowaJvUIoEi0czkGHVXqz_pfrWaX/view?usp=sharing).

**Comment by Slavian2** [comment]
Запустил дебажную сборку. Молча сложилась таким же образом.

**Comment by heinrichI** [comment]
Я бы предложил сделать дамп при падении, но там может гигабайтный файл размером.

**Comment by Slavian2** [comment]
Ну не проблема

Отправлено из мобильной Почты Mail.Ru

суббота, 23 мая 2020 г., 08:19 +0300 от notifications@github.com  <notifications@github.com>:

**Comment by Slavian2** [comment]
Сча студию вкачу и отлажу

**Comment by Slavian2** [comment]
Не собирается из-за отсутствие определения SIMD_VERSION, что приводит к включению несуществующего файла simdversion.h:

![image](https://user-images.githubusercontent.com/65719190/82759488-75acdc80-9df6-11ea-9ede-a5cb20c5435a.png)

**Comment by Slavian2** [comment]
Нашёл батник, заполняющий SIMD_VERSION, корректно запустил, перекопировал simdversion.h в 3rd из 3rd.git, всё собралось; но не запускается ни в отладке, ни без отладки;

![image](https://user-images.githubusercontent.com/65719190/82761022-31263e80-9e00-11ea-8dd4-82bc2359cc92.png)

**Comment by Slavian2** [comment]
Всё собрал и запустил, программа молча упала, exception не перехватился(((

![image](https://user-images.githubusercontent.com/65719190/82761713-3a65da00-9e05-11ea-8cd8-21653647f8b5.png)

**Comment by Slavian2** [comment]
Сорри за спам. В итоге плюсовый код не смог отладить. .NET отладчик отваливается при старте плюсового коа. Зато подцепился с помощью WinDBG.

![image](https://user-images.githubusercontent.com/65719190/82764444-638f6600-9e17-11ea-95f9-39ce1710ba53.png)

Сделал полный и минидамп. Доступно тут - https://yadi.sk/d/JqMx1PxCG4J0lw
Имя файла вытащить из контекста не смог.

**Comment by Slavian2** [comment]
Нашёл. Приаттачил.

![image](https://user-images.githubusercontent.com/65719190/82765055-24174880-9e1c-11ea-94b8-c53baefa44fb.png)

https://yadi.sk/d/JqMx1PxCG4J0lw

![03_srdr_maps_yandex_net 4 _1](https://user-images.githubusercontent.com/65719190/82765041-0d70f180-9e1c-11ea-88ec-afa4e3df6852.png)

**Comment by ermig1979** [comment]
Картинка не грузится что-то.

**Comment by Slavian2** [comment]
> Картинка не грузится что-то.

Какая? Которая 03_srdr_maps? Конечно. На ней и падает) Я натравил программу на папку с фотками, восстановленными с харда.

**Comment by heinrichI** [comment]
Я провел на старой сборке. Добавил её в пути поиска. Ничего не упало.

**Comment by ermig1979** [comment]
У меня тоже не упало. GDIPlus просто отказался ее загружать и все. Впрочем, как и все просмоторщики картинок, какие у меня были установлены на машине.

**Comment by Slavian2** [comment]
Другой файл, на котором падает

![image](https://user-images.githubusercontent.com/65719190/82873601-713f0b80-9f3d-11ea-8ca8-8354ed80aba5.png)

Причём файл занимает 0 байт!!! Неужели в коде нет проверки на нулевой размер?

Или я смотрю не на тот указать? Проверяю имя файла, на котором падение, по pImageData?

**Comment by ermig1979** [comment]
Там выше стоит в bool TTga::Supported(HGLOBAL hGlobal) стоит try ... catch , который ловит это исключение и нормально обрабатывает.

**Comment by Slavian2** [comment]
Да, отключил это исключение.  Упал дальше уже с unhandled exception:

![image](https://user-images.githubusercontent.com/65719190/82890707-4660b180-9f55-11ea-9292-eb285530ff04.png)
![1384802587 1 _13](https://user-images.githubusercontent.com/65719190/82890835-7c059a80-9f55-11ea-9227-97d585d58ecb.jpg)

Файл приаттачил выше, могу загрузить в облако, если что

**Comment by ermig1979** [comment]
Воспроизвел на этом файле. Исправил.

**Comment by Slavian2** [comment]
Коммит будет?

**Comment by Slavian2** [comment]
Забрал из support бранча. Упал теперь на другом файле.
![1384802587 1 _3](https://user-images.githubusercontent.com/65719190/82930622-5a74d500-9f8e-11ea-855e-c914ee06a150.jpg)

**Comment by ermig1979** [comment]
Проверил на этом файле - не падает. Вы точно все пересобрали?

**Comment by Slavian2** [comment]
Пересобирал x64, а отладчик почему-то запускался x86. Не понял, как поставить x64 отладчик. Пересобрал x86. Ещё падает:

![2013-09-28 23-15-01](https://user-images.githubusercontent.com/65719190/83007154-f1d43980-a01b-11ea-9112-c76b1258f3fc.JPG)

**Comment by ermig1979** [comment]
Запустил, не падает. Хотя это изображение достаточно крупного размера (13861х13861), может из-за этого. Сколько памяти в системе у вас?

**Comment by Slavian2** [comment]
![image](https://user-images.githubusercontent.com/65719190/83013591-ec7bec80-a025-11ea-98d6-76add52dd181.png)

Как запустить в x64 режиме в последней студии? Может там не упадём.

**Comment by ermig1979** [comment]
Покопался по коду. Там вполне могла быть утечка памяти при загрузке WebP картинок. Если картинок много, то рано или поздно упало бы. 
Исправил.

**Comment by Slavian2** [comment]
На JPG падать перестал, только генерит периодически обрабатываемые исключения при в функциях LoadBitmap. Также, было много падений на PNG и BMP, но я их просто удалил.
Обратил внимание, что программа не пометила дефектными множество явно битых файлов.
![IMG_5095_5](https://user-images.githubusercontent.com/65719190/83040764-4e4d4e00-a048-11ea-8fc2-48f83adb9fe2.JPG)
![$IBD5UVY_2](https://user-images.githubusercontent.com/65719190/83040793-56a58900-a048-11ea-944c-3775b2b721e7.JPG)
![ntvfootball 1 _5](https://user-images.githubusercontent.com/65719190/83040842-66bd6880-a048-11ea-82f4-679e01b96b75.jpg)
![tiles 4 _134](https://user-images.githubusercontent.com/65719190/83040853-6c1ab300-a048-11ea-8724-9f38a6827789.jpg)
![V355604_CROP1_10](https://user-images.githubusercontent.com/65719190/83040871-7177fd80-a048-11ea-9423-907b7b822aec.jpg)

**Comment by Slavian2** [comment]
Не удалось посмотреть? Или не считаете проблемой?

**Comment by ermig1979** [comment]
Сейчас по сути ищется одна проблема - отсутствие маркера конца *.jpeg файла.  Можно конечно помечать дефектными все картинки, которые не открылись. Это может привести к тому, что картинки с известным разрешением, но в неизвестном внутренним формате будут считаться дефектными. Это может привести к удалению хороших картинок. В прочем это можно сделать опциональным (по умолчанию выключено).

**Comment by Slavian2** [comment]
Если это поведение будет плюс-минус соответствовать возможностям большинства типовых просмотрщиков фотографий (в первую очередь - встроенных в Windows), то нормально. Сделайте опциональную опцию. У меня, к сожалению, целая россыпь таких фото.

**Comment by Slavian2** [comment]
Ну как?

**Comment by ermig1979** [comment]
Сейчас я занят, реализую, как только освобожусь.

**Comment by Wingtiger** [comment]
У меня падает на именах файлов, где есть диакритические знаки. Windows 10 x64 (на всех версиях), когда-то 7 x64, русская.
Про длину пути с именем файла не знаю, вроде бы программа такие пропускает и соответственно не проверяет на похожесть.

**Comment by Slavian2** [comment]
Сам в итоге закодил на C++ + STL.
