### ISSUE TITLE
HEIC photo and .MOV .MP4 video

### ISSUE THREAD

**Issue by RRROMAN123** [ermig1979/AntiDupl#97]
Dear developers, could you add support for HEIC and .MOV .MP4 video (screenshot)
Thank you for your work, convenient program.

**Comment by mervincm** [comment]
Second this. Please HEIC!

**Comment by alexandis** [comment]
+1!
Great program, but now HEIC support is needed so bad.

**Comment by DonMWyatt** [comment]
I too would love to see support for HEIC!

**Comment by matthieu04** [comment]
Same, would love HEIC support. I paid for heic support in windows, maybe you could do the same: if users request specific format that you did not plan to support, you could sell paid plugins

**Comment by Edi61** [comment]
With
https://github.com/ermig1979/AntiDupl/commit/cb7c447425c31f5356ca8a7b8b4c6fe3c1ff900e
https://github.com/ermig1979/AntiDupl/commit/e5225cc0a2cdc8e640abe1697778ed83b69727d0
https://github.com/ermig1979/AntiDupl/commit/1deaa36c6a4c3a2223cfc902d4ea87c8ecc29485
Heic/Heif support was added. Mentioned problems basically also solved with last commits.

Regarding MP4 Video:
Antidupl is made for images not for videos -> This would be a complete new feature request where it must be also defined how to do this. -> I'll close this as completed for now.
