### ISSUE TITLE
Is anyone use AntiDupl.NET in 32 bit Windows?

### ISSUE THREAD

**Issue by ermig1979** [ermig1979/AntiDupl#98]
The development of 32-bit Windows will be stopped soon. The development of AntiDupl for 32-bit and 64-bit Windows takes additional efforts. I have a plan to leave only  support 64-bit Windows in future versions of AntiDupl.NET. Are there any objections?

**Comment by yfdyh000** [comment]
I am not, but I think someone may need it.
Not true, 32-bit is deprecated for OEMs, but it should not stop soon, especially for some non-consumer OS versions.
Any details for difficulties?

**Comment by Edi61** [comment]
With https://github.com/ermig1979/AntiDupl/commit/f90f086d58f0be37064c1fdf6ce25175f9d8fb20 32-bit support is removed. 
For 32-bit Windows please use releases <= AntiDupl.NET v2.3.10.
If for any reason you still need 32-bit please create your own fork
 if you want to include newer updates.
